// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZpPXEqJtM7sj8A-xHTyA-u9pmuwk0NI',
    appId: '1:366609442228:android:aa6d5997823594764fbee1',
    messagingSenderId: '366609442228',
    projectId: 'womensafety-ac903',
    storageBucket: 'womensafety-ac903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcWE39Sg1f97wyw1AJTwRxRrIJ97BlTOM',
    appId: '1:366609442228:ios:730b770dd9f3e6774fbee1',
    messagingSenderId: '366609442228',
    projectId: 'womensafety-ac903',
    storageBucket: 'womensafety-ac903.firebasestorage.app',
    iosBundleId: 'com.example.safetyForWoman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI_IWyrQ2Yl6OXcoU0WKtbOfB9-yfeRlM',
    appId: '1:366609442228:web:1f6f9aeccb50443c4fbee1',
    messagingSenderId: '366609442228',
    projectId: 'womensafety-ac903',
    authDomain: 'womensafety-ac903.firebaseapp.com',
    storageBucket: 'womensafety-ac903.firebasestorage.app',
    measurementId: 'G-KJGF5YZ791',
  );
}
